# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker
#      - run:
#          name: "Install curl"
#          command: apk update && apk add curl curl-dev bash
      - sonarcloud/scan
      - run:
          name: "Build Docker Image"
          command: "docker build -t zeabix/simple-api:${CIRCLE_SHA1} ."
      - run:
          name: "Install trivy"
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run: 
          name: "Scan image"
          command: trivy image --exit-code 1 --severity "CRITICAL,HIGH" --no-progress --format json --output /tmp/scan-report.json zeabix/simple-api:${CIRCLE_SHA1}
      - store_artifacts:
          path: /tmp/scan-report.json
          destination: scan-report

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  simple-workflow:
    jobs:
      - build:
          context: sonarcloud
