# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  code_quality:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Unit Test"
          command: cd src; go test ./... -v
      - run:
          name: "Coverage"
          command: cd src; go test -coverprofile=coverage.out ./... ; go tool cover -func=coverage.out > code_coverage.txt
      - store_artifacts:
          path: src/code_coverage.txt
          destination: code_coverage
      - sonarcloud/scan
  code_scan:
    docker: 
      - image: cimg/node:18.2.0
    steps:
      - checkout
      - setup_remote_docker
      - sonarcloud/scan
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Image"
          command: "docker build -t zeabix/simple-api:${CIRCLE_SHA1} ."
      - run:
          name: "Install trivy"
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - run: 
          name: "Scan image"
          command: trivy image --exit-code 1 --severity "CRITICAL,HIGH" --no-progress  --format table --output /tmp/scan-report.txt zeabix/simple-api:${CIRCLE_SHA1}
      - store_artifacts:
          path: /tmp/scan-report.txt
          destination: scan-report
  stagging:
    docker:
      - image: cimg/go:1.18
    steps:
      - run:
          name: "Mock deploy stagging"
          command: echo "deploy to stagging"
  dast:
    docker:
      - image: circleci/openjdk
    steps:
      - run:
          name: "Install cli"
          command: wget https://zeabixblob1.blob.core.windows.net/blob-container/burp-ci-driver-2021.3-162.jar
      - run:
          name: "Dynamic scan"
          command: java -jar burp-ci-driver-2021.3-162.jar  http://20.24.144.124:8080/ --api-key=QADUrF7dc8k3dPBWrdu72DtDpPateIDc --site-id=1 --min-severity=high --min-confidence=certain --report-file=scan-report.html --report-type=summary
      - store_artifacts:
          path: scan-report.html
          destination: dast-report

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  simple-workflow:
    jobs:
      - code_quality:
          context: sonarcloud
      - code_scan:
          context: sonarcloud
      - build:
          requires: [code_quality]
      - stagging:
          requires: [build]
      - dast:
          requires: [stagging]
