# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker
#      - run:
#          name: "Install curl"
#          command: apk update && apk add curl curl-dev bash
      - sonarcloud/scan
      - run:
          name: "Build Docker Image"
          command: "docker build -t zeabix/simple-api:${CIRCLE_SHA1} ."
      - run:
          name: "Install trivy"
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - run: 
          name: "Scan image"
          command: trivy image --exit-code 1 --severity "CRITICAL,HIGH" --no-progress --format json --output /tmp/scan-report.json zeabix/simple-api:${CIRCLE_SHA1}
      - store_artifacts:
          path: /tmp/scan-report.json
          destination: scan-report
  stagging:
    docker:
      - image: cimg/go:1.18
    steps:
      - run:
          name: "Mock deploy stagging"
          command: echo "deploy to stagging"
  dast:
    docker:
      - image: circleci/openjdk
    steps:
      - run:
          name: "Install cli"
          command: wget https://zeabixblob1.blob.core.windows.net/blob-container/burp-ci-driver-2021.3-162.jar
      - run:
          name: "Dynamic scan"
          command: java -jar ./burp-ci-driver-2021.3-162.jar http://20.24.185.62:8080 --api-key=jVM3K3t5l9QmM6Jmkz9qFwBxQS1Rj28J --site-id=2 --min-severity=high --min-confidence=certain --report-file=scan-report.html --report-type=summary

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  simple-workflow:
    jobs:
      - build:
          context: sonarcloud
      - stagging:
          requires: [build]
      - dast:
          requires: [stagging]
