# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Image"
          command: "docker build -t zeabix/simple-api:${CIRCLE_SHA1} ."
      - run:
          name: "Install trivy"
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run: 
          name: "Scan image"
          command: trivy image --exit-code 0 --no-progress zeabix/simple-api:${CIRCLE_SHA1}

workflows:
  simple-workflow:
    jobs:
      - build
